# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-09 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='hotcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='indian',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='destinationimages',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Destination'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='review',
            name='creator_rating',
            field=models.CharField(choices=[('5', 'Very Good'), ('4', 'Good'), ('3', 'Average'), ('2', 'Poor'), ('1', 'Very Poor')], default='5', max_length=30),
        ),
        migrations.AlterField(
            model_name='things',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waystoreach',
            name='title',
            field=models.CharField(choices=[('AIR', 'By Air'), ('BUS', 'By Bus'), ('TRAIN', 'By Train')], default='AIR', max_length=10),
        ),
    ]
