# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160701_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='continent',
            field=models.CharField(choices=[('ASIA', 'asian countries'), ('AFRICA', 'african countries'), ('AMERICA', 'american countries'), ('AUSTRALIA', 'australian countries'), ('EUROPE', 'europe countries')], default='ASIA', max_length=30),
        ),
    ]
