# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-09 07:27
from __future__ import unicode_literals

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160609_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default={}, upload_to=base.models.destphotoname),
            preserve_default=False,
        ),
    ]
