# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 15:23
from __future__ import unicode_literals

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to=base.models.destphotoname2),
        ),
    ]
