# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-18 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20160618_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='cost',
        ),
    ]
