# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-18 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_itinerary_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
